### ISSUE TITLE
Meta helper not working

### ISSUE THREAD

**Issue by lavdboom** [spatie/laravel-endpoint-resources#34]
Hi! I really like this package, but I can't seem to get the meta helper working.

My resource:
`<
namespace App\DataAccess\Resources;

use Spatie\ResourceLinks\HasLinks;
use Spatie\ResourceLinks\HasMeta;
use Illuminate\Http\Resources\Json\JsonResource;
use App\DataAccess\Resources\AreaResource;
use App\Http\Controllers\TitanController;

class TitanResource extends JsonResource
{
    use HasLinks, HasMeta;

    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        $response = [
            'id' => $this->id,
            'type' => 'titans',
            'attributes' => [
                'name' => $this->name,
                'description' => $this->description,
            ],
            'links' => $this->links(TitanController::class, [
                'titan' => $this->id,
            ]),
        ];

        $response['relationships'] = $this->when($this->relationLoaded('areas'),function()
        {
            $response['areas'] = [
                'data' => AreaResource::collection($this->areas),
            ];
            return $response;
        });

        return $response;
    }

    public static function meta()
    {
        return [
            'links' => self::collectionLinks(TitanController::class)
        ];
    }
}`

My output:
`{
    "data": [
        {
            "id": 1,
            "type": "titans",
            "attributes": {
                "name": "Bionis",
                "description": "The first of the two clashing titans. Its body is home to all organic life forms (Homs, Noppon, animals, etc)."
            },
            "links": {
                "show": "http://xc-api/api/titans/1"
            }
        },
        {
            "id": 2,
            "type": "titans",
            "attributes": {
                "name": "Mechonis",
                "description": "The second of the two clashing titans. Its body is home to all mechanical beings, including the mechanical race known as the Mechon."
            },
            "links": {
                "show": "http://xc-api/api/titans/2"
            }
        }
    ]
}`

Note that that the meta key is missing completely. (I manually add the top level data key after the creation of the resource.) Any suggestions?

**Comment by rubenvanassche** [comment]
Hi @lavdboom,

How do you use the resource within your application? Because your code looks ok to me 🤔

**Comment by rubenvanassche** [comment]
Hi @lavdboom,

We decided to abandon this package, you can read more about it here: https://rubenvanassche.com/laravel-resource-links-two-years-later/
