### ISSUE TITLE
Delete or destroy method?

### ISSUE THREAD

**Issue by thijskok** [spatie/laravel-endpoint-resources#5]
As a default, this package looks for a `delete` method for a given controller. Laravel uses a `destroy` method for resourceful controllers instead (the method is called `destroy`, the actual HTTP verb is `delete` though).

In src/EndpointTypes/ControllerEndpointType.php:

```php
    public function getEndpoints(Model $model = null): array
    {
        $controller = new $this->controller();
        $endpoints = property_exists($controller, 'endPointMethods')
            ? $controller->endPointMethods
            : ['show', 'edit', 'update', 'delete'];
        return $this->resolveEndpoints(
            $endpoints,
            $model
        );
    }
```

This might be intentional, but I suspect it's a typo?

**Comment by rubenvanassche** [comment]
Thanks Thijs it's indeed a typo. Fixed it with e60629f9bd89a15e231f690487ef8d57dd43e149
